# Generated by Django 3.0.5 on 2020-04-26 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sp_accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='serviceprovidername',
            new_name='username',
        ),
    ]
