# Generated by Django 3.0.3 on 2020-04-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=256)),
                ('customer_id', models.CharField(max_length=256)),
                ('list_of_items', models.TextField(max_length=500)),
            ],
        ),
    ]
